/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface RouterInterface extends ethers.utils.Interface {
  functions: {
    "factory()": FunctionFragment;
    "originSwap(address,address,address,uint256,uint256,uint256)": FunctionFragment;
    "viewOriginSwap(address,address,address,uint256)": FunctionFragment;
    "viewTargetSwap(address,address,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "originSwap",
    values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewOriginSwap",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "viewTargetSwap",
    values: [string, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "originSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "viewOriginSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewTargetSwap",
    data: BytesLike
  ): Result;

  events: {};
}

export class Router extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RouterInterface;

  functions: {
    factory(overrides?: CallOverrides): Promise<[string]>;

    "factory()"(overrides?: CallOverrides): Promise<[string]>;

    originSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      _minTargetAmount: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "originSwap(address,address,address,uint256,uint256,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      _minTargetAmount: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    viewOriginSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { targetAmount_: BigNumber }>;

    "viewOriginSwap(address,address,address,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { targetAmount_: BigNumber }>;

    viewTargetSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _targetAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { originAmount_: BigNumber }>;

    "viewTargetSwap(address,address,address,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _targetAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { originAmount_: BigNumber }>;
  };

  factory(overrides?: CallOverrides): Promise<string>;

  "factory()"(overrides?: CallOverrides): Promise<string>;

  originSwap(
    _quoteCurrency: string,
    _origin: string,
    _target: string,
    _originAmount: BigNumberish,
    _minTargetAmount: BigNumberish,
    _deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "originSwap(address,address,address,uint256,uint256,uint256)"(
    _quoteCurrency: string,
    _origin: string,
    _target: string,
    _originAmount: BigNumberish,
    _minTargetAmount: BigNumberish,
    _deadline: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  viewOriginSwap(
    _quoteCurrency: string,
    _origin: string,
    _target: string,
    _originAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "viewOriginSwap(address,address,address,uint256)"(
    _quoteCurrency: string,
    _origin: string,
    _target: string,
    _originAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  viewTargetSwap(
    _quoteCurrency: string,
    _origin: string,
    _target: string,
    _targetAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "viewTargetSwap(address,address,address,uint256)"(
    _quoteCurrency: string,
    _origin: string,
    _target: string,
    _targetAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    factory(overrides?: CallOverrides): Promise<string>;

    "factory()"(overrides?: CallOverrides): Promise<string>;

    originSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      _minTargetAmount: BigNumberish,
      _deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "originSwap(address,address,address,uint256,uint256,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      _minTargetAmount: BigNumberish,
      _deadline: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewOriginSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "viewOriginSwap(address,address,address,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewTargetSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _targetAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "viewTargetSwap(address,address,address,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _targetAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    factory(overrides?: CallOverrides): Promise<BigNumber>;

    "factory()"(overrides?: CallOverrides): Promise<BigNumber>;

    originSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      _minTargetAmount: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "originSwap(address,address,address,uint256,uint256,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      _minTargetAmount: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    viewOriginSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "viewOriginSwap(address,address,address,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    viewTargetSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _targetAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "viewTargetSwap(address,address,address,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _targetAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "factory()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    originSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      _minTargetAmount: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "originSwap(address,address,address,uint256,uint256,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      _minTargetAmount: BigNumberish,
      _deadline: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    viewOriginSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "viewOriginSwap(address,address,address,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _originAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    viewTargetSwap(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _targetAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "viewTargetSwap(address,address,address,uint256)"(
      _quoteCurrency: string,
      _origin: string,
      _target: string,
      _targetAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
